### ISSUE TITLE
Sobol' Sequence Missing First 4 Points

### ISSUE THREAD

**Issue by alegresor** [SciML/QuasiMonteCarlo.jl#78]
Running the following code 
```julia
using QuasiMonteCarlo
QuasiMonteCarlo.sample(4,0,1,SobolSample())
```
yields
```
4-element Vector{Float64}:
 0.375
 0.875
 0.625
 0.125
```
However, the first 4 points in a 1 dimensional Sobol' sample should be [0, .5, .25, .75]. The output are points at index 5 to 8. 
I am looping in my collaborator @FJHickernell, an expert in QMC methods who will be valuable to this discussion.

**Comment by dmetivie** [comment]
I believe this is caused by the “famous” debate about starting the Sobol sequence at zero (-> theory) or not (-> practical implementation). 
`QuasiMonteCarlo.jl` uses `Sobol.jl` which use the latter convention (drop zero), see related [issue](https://github.com/JuliaMath/Sobol.jl/issues/31) and refs therein (Owen' paper). 
This debate was started way back I believed and amplified with Pytorch using the drop zero solution. @fjhickernell probably knows better.

Meanwhile, a while ago, I ported the R Owen (@dcarrera you suggested that at some point) code to do scrambling in a package [RandomizedQuasiMonteCarlo.jl](https://github.com/dmetivie/RandomizedQuasiMonteCarlo.jl). 
There, you can find the implementation starting at zero. 

Note: I don't maintain the package anymore since all its features have been moved in `QuasiMonteCarlo.jl` (excepted the following function, in fact).

```julia
using RandomizedQuasiMonteCarlo
m = 2
N = 2^m # Number of points
d = 1 # dimension
b = 2 # always 2 for Sobol
M = 32 # number of bits to encode points
unrandomized_bits = sobol_pts2bits(m, d, M) 
u_sobol = dropdims(mapslices(bits2unif, unrandomized_bits, dims=3), dims=3)
```
yields 
```julia
4×1 Matrix{Rational{Int64}}:
 0//1
 1//2
 1//4
 3//4
```

I believe this convention should be specified somewhere in bold in `Readme.md` and docs.

**Comment by alegresor** [comment]
Thank you for the quick response. I'll close this issue and monitor the other one you linked.
